# Generated by Django 5.1.3 on 2024-12-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.AlterField(
            model_name='board',
            name='b_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
