# Generated by Django 5.1.3 on 2024-12-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_id_alter_board_b_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bfile',
            field=models.ImageField(null=True, upload_to='board'),
        ),
    ]
