# Generated by Django 5.1.3 on 2024-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_b_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bfile',
            field=models.ImageField(blank=True, null=True, upload_to='board'),
        ),
    ]
