# Generated by Django 5.1.3 on 2024-12-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_rename_bfile_board_b_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
