# Generated by Django 5.1.3 on 2024-12-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_board_like_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='like_member',
            new_name='b_like_members',
        ),
    ]
