# Generated by Django 5.1.3 on 2024-12-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_board_b_dislike_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='b_file',
        ),
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_file', models.ImageField(blank=True, null=True, upload_to='board/')),
                ('b_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='b_file',
            field=models.ManyToManyField(blank=True, to='board.boardfile'),
        ),
    ]
