# Generated by Django 5.1.3 on 2024-12-04 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0010_alter_board_b_date'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('c_pw', models.CharField(blank=True, max_length=10, null=True)),
                ('c_content', models.TextField()),
                ('c_date', models.DateTimeField(auto_now=True)),
                ('c_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('c_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
    ]
