# Generated by Django 5.1.3 on 2024-12-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_board',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_member',
            new_name='member',
        ),
    ]
