# Generated by Django 5.1.3 on 2024-12-12 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_c_board_comment_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
    ]
