# Generated by Django 5.1.3 on 2024-12-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_no',
            field=models.IntegerField(default=1),
        ),
    ]
