# Generated by Django 5.1.3 on 2024-12-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_b_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.AlterField(
            model_name='board',
            name='b_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
