# Generated by Django 5.1.3 on 2024-12-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_username', models.CharField(max_length=10)),
                ('m_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m_password', models.CharField(max_length=20)),
                ('m_nickName', models.CharField(max_length=15)),
                ('m_gender', models.CharField(max_length=5)),
                ('m_date', models.DateField(auto_now=True)),
                ('m_auth', models.IntegerField(default=1)),
            ],
        ),
    ]
