# Generated by Django 5.1.3 on 2024-12-05 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_member_m_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_inform',
            fields=[
                ('l_no', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=10)),
                ('l_description', models.TextField()),
                ('l_location', models.CharField(max_length=30)),
                ('l_file', models.ImageField(null=True, upload_to='board')),
                ('l_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
            ],
        ),
    ]
