# Generated by Django 5.1.3 on 2024-12-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_remove_board_b_file_board_bfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='bfile',
            new_name='b_file',
        ),
    ]
