# Generated by Django 5.1.3 on 2024-12-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_rename_like_member_board_b_like_members'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='b_dislike_members',
            field=models.ManyToManyField(default='', related_name='dislike_member', to='member.member'),
        ),
    ]
