# Generated by Django 5.1.3 on 2024-12-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_remove_board_b_file_boardfile_board_b_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_header',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
