# Generated by Django 5.1.3 on 2024-12-13 09:18

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('e_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food_inform',
            fields=[
                ('f_no', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=10)),
                ('f_description', models.TextField()),
                ('f_file', models.ImageField(null=True, upload_to='board')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('s_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('s_address', models.CharField(max_length=100, null=True)),
                ('s_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KR')),
                ('s_file', models.ImageField(null=True, upload_to='board/')),
                ('s_foodname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food_inform')),
            ],
        ),
    ]
