# Generated by Django 5.1.3 on 2024-12-13 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lo_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location1',
            fields=[
                ('lo_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location_inform',
            fields=[
                ('l_no', models.AutoField(primary_key=True, serialize=False)),
                ('l_location', models.CharField(max_length=30)),
                ('l_description', models.TextField(null=True)),
                ('l_subtitle', models.CharField(max_length=50, null=True)),
                ('l_file', models.ImageField(null=True, upload_to='board/')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('a_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('a_description', models.TextField(null=True)),
                ('a_file', models.ImageField(null=True, upload_to='board/')),
                ('a_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location_inform')),
            ],
        ),
    ]
